home/urls.py
from django.urls import path

from . import views
app_name='home'
urlpatterns=[
    path('',views.home_func,name='home-func')
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blogs.urls')),
    path('contactus/',include('contactus.urls')),
    path('home/',include('home.urls',namespace='home-namespace'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title_page %}
            Page ....
        {% endblock %}
    </title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" >

    {% block header_reference %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'app.css' %}">
</head>
<body>
    <header id="main-navigation">
        <h1><a href="{% url 'starting_page' %}">MySite</a></h1>
        <nav><a href="{% url 'post_page' %}">All Post</a></nav>
    </header>
    {% include 'navbar.html' %}
    {% block content_page %}
        Hello User
    {% endblock %}

    {% block footer_reference %}
    {% endblock %}

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">

        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home-namespace:home-func' %}">Home</a>

        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'contact-us' %}">register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact-us' %}">login</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact-us' %}">logout</a>
        </li>

      </ul>
    </div>
  </div>
</nav>